# Generating arbitrary data

First thing that one need while experimenting with linear algebra library is having data of arbitrary shape, following numpy methods are helpful in generating data to play with.
* `array`
* `zeros`
* `arange`
* `linspace`

For generating random data use

* `random.randn`

In [68]:
import numpy as np
#Generating from python collections
da = np.array([1,2,3])
print(da)
#Generating zeros of a given shape
#helpful for testing for shapes
dz = np.zeros((2,3), dtype=int)
print(dz)
#Generates a arithmetic progression
#start, stop, step
dr = np.arange(10,20,2)
print(dr)
#Generates evenly spaced specifed number of data points between 2 endpoints
ds = np.linspace(10, 20, 3)
print(ds)
#Generate random data of given shape
dr = np.random.randn(2,3)
print(dr)

[1 2 3]
[[0 0 0]
 [0 0 0]]
[10 12 14 16 18]
[ 10.  15.  20.]
[[-0.87105618  0.84750507 -1.47266116]
 [-0.41331751 -0.20391767 -0.0409101 ]]


# Shape
what *types* are for a general programming, *shape* are for numerical programming. Getting them right goes a long way in having a bug free program
numpy `shape` and `reshape` are useful methods to work around with shapes


In [34]:
dz = np.zeros((2,4), dtype=int)
print(dz)
print(dz.shape)
print(dz.shape[0])
dz.reshape(2,2,2)
#specifying -1 
dz.reshape(2,-1)
#using tuple or variadic argument for shape
dz.reshape((2,-1)) # is same as dz.reshape(2,-1)

[[0 0 0 0]
 [0 0 0 0]]
(2, 4)
2


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

# Transpose

In [41]:
dz = np.zeros((2,4), dtype=int)
dz_transpose = dz.transpose()
dz_transpose.shape

(4, 2)

# Dot Product

In [56]:
A = np.array([1,2,3]).reshape(3,1)
Y = np.array([1,2,3]).reshape(3,1)
print(A.shape)
print(Y.shape)
np.dot(A,Y)

(3, 1)
(3, 1)


ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

# Sum

In [66]:
A = np.array([1,2,3])
s = np.sum(A)
print(s)
a = np.zeros((3,4))
print(a)
b = np.ones((4,1))
a.transpose()+b

6
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# Multiply

In [53]:
w = np.zeros((5,1))
x = np.zeros((5, 7))
np.multiply(w, x)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [69]:
w = np.array([1,1,1])
np.tanh(w)
w

array([ 0.76159416,  0.76159416,  0.76159416])