## Datatypes in python

In [7]:
a = 1.0
b = 1
c = 'aaaa'

print(type(a))
print(type(b))
print(type(c))

<class 'float'>
<class 'int'>
<class 'str'>


## `ndarray` and `dtype` in numpy

In [25]:
import numpy as np

#a is a ndarray with dtype int64 
a = np.array([1,2,3,4])
print(type(a))
print(a.dtype)
print(type(a[0]))
print(repr(a)) #printable representation of object

#explicitly specifying the dtype
a = np.array([4,5,6,7], dtype= np.int16)
print(repr(a)) 

<class 'numpy.ndarray'>
int64
<class 'numpy.int64'>
array([1, 2, 3, 4])
array([4, 5, 6, 7], dtype=int16)


## Scalar, Vector, Matrix, Tensor (conceptually)


In [34]:
#scalar
s = 1

#vector
v = [1,2,3,4]

#matrix 
m = [[11,12,13,14],[21,22,23,24],[31,32,33,34]]

#tensor
t = [[[111,112,113,1114],[121,122,123,124],[131,132,133,134]], [[211,212,213,2114],[221,222,223,224],[231,232,233,234]]]

print(s)
print(v[0])
print(m[0][0])
print(t[0][0][0])


1
1
11
111


## Dimensions (or Shape)
    1. scalar (1 X 1)
    2. vector
        a. row vector (r X 1)
        b. column vector (1 X c)
    3. matrix (r X c)
    4. tensor (a X b X c ....)

## Scalar, Vector, Matrix, Tensor (numpy)

In [58]:
#Vector, Matrix, Tensor are just different arrangement of array of elements 

a = np.array([111,112,113,1114,121,122,123,124,131,132,133,134,211,212,213,2114,221,222,223,224,231,232,233,234])
print(type(a))
print(len(a))
row_vector = np.reshape(a, (1,24))
column_vector = np.reshape(a, (24,1))
matrix = np.reshape(a, (6, 4))
tensor1 = np.reshape(a, (2,3,4))
tensor2 = np.reshape(a, (2,2,3,2))

# print(repr(row_vector))
# print(repr(column_vector))
# print(repr(matrix))
# print(repr(tensor1))
# print(repr(tensor2))

print(row_vector.shape)
print(column_vector.shape)
print(matrix.shape)
print(tensor1.shape)
print(tensor2.shape)


<class 'numpy.ndarray'>
24
(1, 24)
(24, 1)
(6, 4)
(2, 3, 4)
(2, 2, 3, 2)
(24,)


## Numpy Array with Shape (n, ), (1,n) , (n,1)

In [69]:
a = np.array([1,2,3,4])
print(a.shape)
b = np.reshape(a, (1,4))
print(b.shape)
c = np.reshape(a, (4,1))
print(c.shape)

# (n,) is the shape telling that we need only one index to access the elements of `a`
# this is default shape of ndarray. This can be reshaped into dimensions of our choice
# reshaping does not cause any data movement, it just creates a view on top of the storage
print(a[2])

#for (1,n) shape we need 2 indices for element access, even though the data is in one axis
print(b[0]) #acceses the whole row
print(b[0][2]) #acceses 3rd element of the row


(4,)
(1, 4)
(4, 1)
3
[1 2 3 4]
3


In [72]:
print(a.shape)

(4,)
