 ## Functions

In [1]:
def square(x):
    #TBD
    pass

def times2(x):
    #TBD
    pass

def average(x1, x2, x3, x4, x5):
    #TBD
    pass

print(times2(10) == 20)
print(square(6) == 36)
print(average(1,2,3,4,5) == 3.0)



False
False
False


## Reverse engineering functions

In [2]:
  
'''
+--------+--+--------+--+--------+--+--------------+
| f1     |  | f2     |  | f3     |  | f4           |
+--------+  +--------+  +--------+  +--------------+
| x | y  |  | x | y  |  | x  | y |  | x1 | x2 | y  |
+---+----+  +---+----+  +----+---+  +----+----+----+
| 3 | 6  |  | 3 | 6  |  | 1  | 0 |  | 2  | 3  | 4  |
+---+----+  +---+----+  +----+---+  +----+----+----+
| 7 | 14 |  | 7 | 28 |  | 7  | 1 |  | 8  | 5  | 9  |
+---+----+  +---+----+  +----+---+  +----+----+----+
| 8 | 16 |  | 4 | 10 |  | 3  | 1 |  | 6  | 4  | 7  |
+---+----+  +---+----+  +----+---+  +----+----+----+
| 1 | 2  |  | 1 | 1  |  | 2  | 1 |  | 10 | 2  | 7  |
+---+----+  +---+----+  +----+---+  +----+----+----+
| 5 | 10 |  | 9 | 45 |  | 9  | 0 |  | 4  | 2  | 4  |
+---+----+  +---+----+  +----+---+  +----+----+----+
| 9 | 18 |  | 6 | 21 |  | 12 | 0 |  | 16 | 7  | 15 |
+---+----+--+---+----+--+----+---+--+----+----+----+
'''
def f1(x):
    #TBD
    pass

def f2(x):
    #TBD
    pass


def f4(x1, x2):
    #TBD
    pass


print(f1(11) == 22)
print(f2(5) == 15.0)
print(f4(10, 7) == 12.0)

False
False
False


## Software 2.0?
[Andrej Karpathy](https://medium.com/@karpathy/software-2-0-a64152b37c35)

 - 1.0
     - Function
     - Specifications, Code, small {X,Y} which is used to test specs
     - Code
     - Concrete Answers
 - 2.0 
     - ???
     - Large {X,Y} which is used to learn/test a model
     - ???
     - Soft Answers

### Machine Learning and Software 2.0

### Types of ML
    1. Supervised Learning
        - Regression
        - Classification
    2. Unsupervised Learning
    3. Reinforcement Learning

### When to apply ML?
    1. ???
    2. ???
    3. ???


### Features, Signals, Attributes, *x*
 - Text as features
 - Videos, Pictures as features
 - Time as features
 
### Label, Targets, *y*

### *x* and *y* 

### *X* and *Y*

### *n* and *N*

### Dimensionality

## This Class:

### What Level?
 - Input: Numbers.
 - Models: Some canned, Some from scratch
 - Evaluation: Some canned, Some from scratch
 
### Deep Dives
 - ML Evaluation Metrics
 - Linear Regression
 - Neural Network (Back Propogation Algorithm)
 - Collaborative Filtering
 - Graph Centrality

## Regression (Predicting House Prices)


In [3]:
'''
Load Boston, house price dataset
'''
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
import numpy as np

boston = datasets.load_boston()

# print(f'Boston dataset info: {boston.keys()}')
# print(f'Dataset Description ==> {boston["DESCR"]}\n==========\n')
# print(f'X ==> boston["data"]')
# print(f'Y ==> boston["target"]')

# print(f'features ==> {boston["feature_names"]}')
# print(f'n ==> {len(boston["feature_names"])}')
# print(f'N ==> {len(boston["data"])}')
# print(f'Shape of X ==> {boston["data"].shape}')
# print(f'Shape of Y ==> {boston["target"].shape}')
# print(f"First data point: x, X[0]: {boston.data[0]}")
# print(f"First label: y, Y[0]: {boston.target[0]}")


N = 500
X_train = boston.data[:N]
Y_train = boston.target[:N]
X_test = boston.data[500:]
Y_test = boston.target[500:]

model = linear_model.LinearRegression()

#TBD 1: Fit the model to training data

#TBD 2: Use fitted model to predict the house prices of houses in test data 
predictions = []

print(f"Predicted values: {predictions}")
print(f"Actual values: {Y_test}")


Predicted values: []
Actual values: [16.8 22.4 20.6 23.9 22.  11.9]


## Classification (Detecting Spam)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model.logistic import LogisticRegression
import numpy as np

'''
Building a labelled dataset of documents
'''
doc0 = "hello world"
doc1 = "foo bar"
doc2 = "lottery prize winner"
docs_train = [doc0] * 100 + [doc1] * 100 + [doc2] * 4 
docs_test = [
             "lottery winner",
             "hello foo", 
             "hello bar", 
             "lottery prize", 
             "world foo",
             "prize winner",
            ]
'''
    Converting documents to feature vectors
'''

vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(docs_train).toarray()
features = vectorizer.get_feature_names()
print(f'Features: {features}')
# print(f'X_train:\n====\n{X_train}\n====\n')
Y_train = np.array([[0] * 100 + [0] * 100 + [1.0] * 4]).reshape(204,)
#print(f'Y_train:\n====\n{Y_train}\n====\n')

X_test = vectorizer.transform(docs_test).toarray(docs_test)
print(f'X_test:\n====\n{X_test}\n====\n')

'''
Choosing the model
'''
classifier = LogisticRegression()


'''
    Train the model
'''
#TBD Fit the model to training data

'''
    Test the model
'''
#TBD Use fitted model to predict if the documents in test data are spam or not
predictions = []
print(f'Spam classification (1 means document is spam):\n====\n{predictions}\n====\n')

Features: ['bar', 'foo', 'hello', 'lottery', 'prize', 'winner', 'world']
X_test:
====
[[0 0 0 1 0 1 0]
 [0 1 1 0 0 0 0]
 [1 0 1 0 0 0 0]
 [0 0 0 1 1 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 1 1 0]]
====

Spam classification (1 means document is spam):
====
[]
====



## Recommendation (Similar Documents)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestNeighbors
import numpy as np

'''
Building a dataset of documents
'''

'''
    Traing docs
'''
doc0 = "hello hello world "
doc1 = "hello world world"
doc2 = "hello world hello world"
doc3 = "foo foo bar "
doc4 = "foo bar bar"
doc5 = "foo bar foo bar"
doc6 = "lottery prize winner"
doc7 = "lottery prize"
doc8 = "lottery lottery lottery prize winner"
docs_train = [doc0, doc1, doc2, doc3, doc4, doc5, doc6, doc7, doc8]

'''
    Test docs
'''
doct0 = "foo bar"
doct1 = "lottery prize hello"
docs_test = [doct0, doct1]


'''
    Converting documents to feature vectors
'''
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(docs_train).toarray()
features = vectorizer.get_feature_names()
print(f'Features: {features}')
print(f'X_train:\n====\n{X_train}\n====\n')
X_test = vectorizer.transform(docs_test).toarray()
print(f'X_test:\n====\n{X_test}\n====\n')

'''
Choosing the model
'''
model = NearestNeighbors(n_neighbors=3, algorithm='brute')

'''
    Train the model
'''
#TBD

'''
    Test the model, by getting  k=3 most similar documents, and their distances to the ones in test docs 
'''
#TBD
indices, distances = (0,0)

print(f'Indices of nearest documents:\n====\n{indices}\n====\n')
print(f'Distances of nearest documents:\n====\n{distances}\n====\n')


Features: ['bar', 'foo', 'hello', 'lottery', 'prize', 'winner', 'world']
X_train:
====
[[0 0 2 0 0 0 1]
 [0 0 1 0 0 0 2]
 [0 0 2 0 0 0 2]
 [1 2 0 0 0 0 0]
 [2 1 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [0 0 0 1 1 1 0]
 [0 0 0 1 1 0 0]
 [0 0 0 3 1 1 0]]
====

X_test:
====
[[1 1 0 0 0 0 0]
 [0 0 1 1 1 0 0]]
====

Indices of nearest documents:
====
0
====

Distances of nearest documents:
====
0
====



## Anomaly Detection (Detecting Fraud Transactions)

In [11]:
import random

'''
features = ["amount_category", "merchant_web_mobile", "dow",  "hour" ]
feature description
    amount_category       0 if amount < £100
                          1 if  £100 <= amount < £500)
                          2 if  £500 <= amount

    merchant_web_mobile   0 if  transaction done in shop
                          1 if  transaction done through web
                          2 if  transaction done through mobile    
    
    dow                   transaction day of week (1-7)
    hour                  transaction hour (1-24)
'''
def normal_txn_hour():
    return random.randint(9,18)
def normal_txn_dow():
    return random.randint(1,5)

'''
Building a hypothetical dataset of normal transactions
'''
N = 1000
X_train = [[0, 0, normal_txn_dow(), normal_txn_hour()] for i in range(N)]
# print(*X_train, sep = "\n")

'''
Building a hypothetical test dataset: some fraud transactions and some normal
'''
X_test = [
    [1,2,6,23],
    [1,2,6,23],
    [0,0,2,11],
]

'''
Choosing a model
'''
from sklearn.covariance import EllipticEnvelope
model = EllipticEnvelope()

'''
    Train the model so that it understand whats normal transaction
'''

#TBD


'''
   Use the trained model to predict if the given transactions are fraudlent or not
'''

#TBD 
predictions = []


print(f'Fraud Transaction Prediction (-1 means anomaly/outlier i.e fraud):\n====\n{predictions}\n====\n')



Fraud Transaction Prediction (-1 means anomaly/outlier i.e fraud):
====
[]
====



## Graph Analytics (Important nodes in the network)
qualitative treatment
 - truths  (Select <attributes> from where <filter> )
 - deeper truths (Select <agg> from where <filter> group by)
 - revelations (page_rank(G(n)) )
concept of centrality
    
### Expressing problems as Graph
- Social Network, transport, communication, infrasturucture, documents
- Links
- Software 2.0 approach (express problem as a graph & apply graph algorithms)