# Try your own stuff here

## Hello World

In [13]:
print("hello world")

hello world


 ## Expressions

In [1]:
5 * 10

50

 ## Functions

In [4]:
def times(x1, x2):
    return x1*x2

times(5, 10)

50

 ## Matrix Multiplication

In [14]:
import numpy as np

m1 = np.random.randint(low=1, high=3, size=(4,5))
print(m1)
m2 = np.random.randint(low=1, high=3, size=(5,7))
print(m2)
np.matmul(m1,m2)


[[2 1 2 2 2]
 [1 1 2 2 1]
 [2 2 2 1 1]
 [1 1 1 2 1]]
[[1 1 2 2 2 1 2]
 [2 1 2 2 2 2 2]
 [1 2 1 1 2 2 2]
 [2 1 1 2 1 2 2]
 [1 2 2 2 1 1 1]]


array([[12, 13, 14, 16, 14, 14, 16],
       [10, 10, 10, 12, 11, 12, 13],
       [11, 11, 13, 14, 14, 13, 15],
       [ 9,  8,  9, 11,  9, 10, 11]])