## Train Test Split

### Simple train test split

In [73]:
from sklearn.model_selection import train_test_split
import numpy as np

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [6, 7], [8, 9], [9, 10], [11, 12]])
Y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

[[ 1  2]
 [ 3  4]
 [ 3  4]
 [ 1  2]
 [ 8  9]
 [11 12]]
[0 0 1 0 2 2]
[[ 6  7]
 [ 5  6]
 [ 9 10]]
[1 1 2]


### Kfold train test split

In [76]:
from sklearn.model_selection import KFold
import numpy as np

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [6, 7], [8, 9], [9, 10], [11, 12]])
Y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
kf = KFold(n_splits=3)

print(kf)  
for train_index, test_index in kf.split(X, Y):
   print("train indices:", train_index, "test indices:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   Y_train, Y_test = Y[train_index], Y[test_index]
#    print(X_train)

KFold(n_splits=3, random_state=None, shuffle=False)
train indices: [3 4 5 6 7 8] test indices: [0 1 2]
train indices: [0 1 2 6 7 8] test indices: [3 4 5]
train indices: [0 1 2 3 4 5] test indices: [6 7 8]


### Stratified KFold split: Classes are distributed across the splits

In [77]:
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [6, 7], [8, 9], [9, 10], [11, 12]])
Y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
skf = StratifiedKFold(n_splits=3)

print(skf)  
for train_index, test_index in skf.split(X, Y):
   print("train indices:", train_index, "test indices:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]


StratifiedKFold(n_splits=3, random_state=None, shuffle=False)
train indices: [1 2 4 5 7 8] test indices: [0 3 6]
train indices: [0 2 3 5 6 8] test indices: [1 4 7]
train indices: [0 1 3 4 6 7] test indices: [2 5 8]


## Hyperparameter Tuning

### Varying neural networks hyperparams

In [72]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.wrappers.scikit_learn import KerasClassifier
from keras.datasets import mnist
from keras.optimizers import SGD
from keras.utils import np_utils

seed = 1
np.random.seed(seed)

def create_model():
    model = Sequential()
    model.add(Dense(40, activation='relu', input_shape=(28*28,)))
    model.add(Dense(20, activation='relu'))
    model.add(Dense(10, activation='sigmoid'))
    model.compile(loss='categorical_crossentropy',
                optimizer=SGD(),
                metrics=['accuracy'])
    model.summary()
    return model

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 28*28)
X_test = X_test.reshape(10000, 28*28)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalize
X_train = X_train/255
X_test = X_test/255

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# Encode Y as binary class vector
Y_train = np_utils.to_categorical(Y_train, 10)
Y_test = np_utils.to_categorical(Y_test, 10)

X = X_train
Y = Y_train

#Wrapper to make keras model work with scikitlearn
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
batch_size = [32, 50, 100]
epochs = [5, 7, 10]

param_grid = dict(batch_size=batch_size, epochs=epochs)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv = 3)
grid_result = grid.fit(X, Y)

# # summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

60000 train samples
10000 test samples
Best: 0.940700 using {'batch_size': 32, 'epochs': 10}
0.917533 (0.004669) with: {'batch_size': 32, 'epochs': 5}
0.929517 (0.001445) with: {'batch_size': 32, 'epochs': 7}
0.940700 (0.001471) with: {'batch_size': 32, 'epochs': 10}
0.913233 (0.003233) with: {'batch_size': 50, 'epochs': 5}
0.919100 (0.003311) with: {'batch_size': 50, 'epochs': 7}
0.929033 (0.002597) with: {'batch_size': 50, 'epochs': 10}
0.891650 (0.001961) with: {'batch_size': 100, 'epochs': 5}
0.899700 (0.005700) with: {'batch_size': 100, 'epochs': 7}
0.910833 (0.001978) with: {'batch_size': 100, 'epochs': 10}


### Varying neural network's layers and neurons

In [81]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.wrappers.scikit_learn import KerasClassifier
from keras.datasets import mnist
from keras.optimizers import SGD, Adam
from keras.utils import np_utils

seed = 1
np.random.seed(seed)

def create_model(model_conf):
    model = Sequential()

    #add hidden layers 
    #print('building nn with conf' + str(model_conf))
    hidden_layers = model_conf['hidden_layers']
    n_h1 = hidden_layers[0]['neurons'] 
    n_h1_activation = hidden_layers[0]['activation']
    model.add(Dense(n_h1, activation=n_h1_activation, input_shape=(28*28,)))
    for layer in hidden_layers[1:]:
        neurons = layer['neurons']
        activation = layer['activation'] 
        model.add(Dense(neurons, activation=activation))
    
    #add output_layer     
    model.add(Dense(10, activation='sigmoid'))
    optimizer = model_conf['optimizer']
    model.compile(loss='categorical_crossentropy',
                optimizer=optimizer,
                metrics=['accuracy'])

    model.summary()
    return model


(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 28*28)
X_test = X_test.reshape(10000, 28*28)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalize
X_train = X_train/255
X_test = X_test/255

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# Encode Y as binary class vector
Y_train = np_utils.to_categorical(Y_train, 10)
Y_test = np_utils.to_categorical(Y_test, 10)

X = X_train
Y = Y_train

#Wrapper to make keras model work with scikitlearn
model = KerasClassifier(build_fn=create_model, verbose=0)
# define the grid search parameters

batch_size = [32]
epochs = [5]
model_conf = [
    { "hidden_layers": [{"neurons": 40, "activation": "relu"},
                         {"neurons": 20, "activation": "relu"}
                        ],
       "optimizer": SGD(lr=0.005)
    },
    { "hidden_layers": [{"neurons": 30, "activation": "relu"},
                         {"neurons": 15, "activation": "relu"},
                        ],
       "optimizer": SGD(lr=0.005)
    },
    { "hidden_layers": [{"neurons": 60, "activation": "relu"},
                         {"neurons": 50, "activation": "relu"},
                        {"neurons": 40, "activation": "relu"},
                        {"neurons": 30, "activation": "relu"},
                        {"neurons": 20, "activation": "relu"}
                       ],
       "optimizer": SGD()
    },
    { "hidden_layers": [{"neurons": 40, "activation": "relu"},
                         {"neurons": 20, "activation": "relu"}
                        ],
       "optimizer": Adam()
    }


]

param_grid = dict(batch_size=batch_size, epochs=epochs, model_conf=model_conf)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv = 2, refit=False)
grid_result = grid.fit(X, Y)


print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

60000 train samples
10000 test samples
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_296 (Dense)            (None, 40)                31400     
_________________________________________________________________
dense_297 (Dense)            (None, 20)                820       
_________________________________________________________________
dense_298 (Dense)            (None, 10)                210       
Total params: 32,430
Trainable params: 32,430
Non-trainable params: 0
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_299 (Dense)            (None, 40)                31400     
_________________________________________________________________
dense_300 (Dense)            (None, 20)                820       
_________________________________

## Feature Normalization

In [79]:
from sklearn import preprocessing
import numpy as np

X = np.array([[1000, 2, 0.0001], [2000, 4, 0.0003], [3000, 2, 0.0005]])
scaled_X = preprocessing.scale(X)
print(scaled_X)

[[-1.22474487 -0.70710678 -1.22474487]
 [ 0.          1.41421356  0.        ]
 [ 1.22474487 -0.70710678  1.22474487]]


## Evaluation Metrics

In [45]:
#Mean Squared Error for Regression
from sklearn.metrics import mean_squared_error
Y = [100, 200, 300, 400]
Y_hat = [102, 198, 300, 405]

mse = mean_squared_error(Y, Y_hat)
print(mse)

8.25


In [50]:
#Accuracy for Classification Problems
from sklearn.metrics import accuracy_score
Y = [1, 1, 0, 0, 1]
Y_hat = [1, 1, 0, 0, 0 ]
accuracy = accuracy_score(Y, Y_hat)
print(accuracy)

0.8


In [61]:
#Evaluation metrics for skewed classes
from sklearn.metrics import accuracy_score
# 0 is normal class 1 is nearly outlier class
Y = [ 0 for i in range(1000)] + [1 for i in range(10)]

def dumb_classifier_predict(N):
    #returns class 0 for everything except some random ones
    res = [0 for i in range(N)]
    res[0] = res[5] = res[1002] = 1
    return res

Y_hat = dumb_classifier_predict(1010)

accuracy = accuracy_score(Y, Y_hat)
print('accuracy=', accuracy)
#even dumb classifiers can have high accuracy in skewed class scenarios
#Use precision and recall
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(Y, Y_hat)
print('precision =', precision)
recall = recall_score(Y, Y_hat)
print('recall =', recall)

#For single valued metric on skewed classes use F1 score which combines precision and recall
f1 = f1_score(Y, Y_hat)
print('f1 score =',f1)

#Confusion metrics
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y, Y_hat))



accuracy= 0.9891089108910891
precision = 0.3333333333333333
recall = 0.1
f1 score = 0.15384615384615383
[[998   2]
 [  9   1]]


In [71]:
#Confusion matrix for multiclass classification
import random
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

Y = [ 0 for i in range(1000)] + [1 for i in range(1000)] + [2 for i in range(1000)] + [3 for i in range(1000)] + [4 for i in range(1000)]
Y_hat = [ random.randint(0,4) for i in range(5000)]

#Confusion matrix for multiclass classification
print(confusion_matrix(Y, Y_hat))

#Precision, Recall, F1 score for each class
print(precision_recall_fscore_support(Y, Y_hat))

[[206 179 217 197 201]
 [210 190 202 200 198]
 [183 204 207 209 197]
 [186 196 192 216 210]
 [197 191 207 202 203]]
(array([0.20977597, 0.19791667, 0.20195122, 0.2109375 , 0.2011893 ]), array([0.206, 0.19 , 0.207, 0.216, 0.203]), array([0.20787084, 0.19387755, 0.20444444, 0.21343874, 0.20209059]), array([1000, 1000, 1000, 1000, 1000]))
